# Generated by Django 4.0.5 on 2022-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('author', models.TextField(max_length=50)),
                ('subject_area', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('shelf_number', models.CharField(max_length=10)),
            ],
        ),
    ]
