# Generated by Django 4.0.5 on 2022-06-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('author', models.TextField(max_length=50)),
                ('subject_area', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('shelf_number', models.CharField(max_length=10)),
                ('borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='borrowed_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.BooleanField()),
                ('book_name', models.CharField(default='', max_length=100)),
                ('student', models.CharField(max_length=100)),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField(null=True)),
                ('penalty_due', models.IntegerField(default=0)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Library.book')),
            ],
        ),
    ]
