# Generated by Django 4.0.5 on 2022-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
