# Generated by Django 4.0.5 on 2022-06-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Library', '0002_student_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='someone@gmail.com', max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Samson', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Wanendeya', max_length=50),
        ),
    ]
